apiVersion: v1
kind: Namespace
metadata:
  name: dev-test
  labels:
    istio-injection: enabled
  
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
  namespace: dev-test

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
 name: fabric8-rbac
subjects:
 - kind: ServiceAccount
   # Reference to upper's `metadata.name`
   name: build-robot
   # Reference to upper's `metadata.namespace`
   namespace: dev-test
roleRef:
 kind: ClusterRole
 name: cluster-admin
 apiGroup: rbac.authorization.k8s.io
