

apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "jwt-example"
  namespace: dev-test
spec:
  selector:
    matchLabels:
      app: dev-server
  jwtRules:
  - issuer: "testing@secure.istio.io"
    jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.5/security/tools/jwt/samples/jwks.json"

---

apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "frontend-ingress"
  namespace: dev-test
spec:
  selector:
    matchLabels:
      app: dev-server
  action: DENY
  rules:
  - from:
    - source:
        notRequestPrincipals: ["*"]
